import os
import io
import base64
import tempfile
from datetime import datetime, timezone
from fpdf import FPDF
from PIL import Image

class CivilCortexPDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 18)
        self.set_text_color(0, 51, 102) # Dark blue
        self.cell(0, 10, "CIVILCORTEX ENGINEERING REPORT", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("helvetica", "I", 10)
        self.set_text_color(128, 128, 128)
        self.cell(0, 8, "Structural Health Assessment & Remediation Strategy", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(6)

    def footer(self):
        self.set_y(-25)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 8, "Generated by CivilCortex Multi-Agent Structural Health Platform", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}", border=False, align="C")

def sanitize_text(text: str) -> str:
    """Sanitizes text for standard PDF latin-1 output."""
    if not text:
        return ""
    # Replace Rupee symbol and non-latin symbols with compatible strings
    text = text.replace("₹", "INR ").replace("–", "-").replace("—", "-")
    text = text.replace("“", '"').replace("”", '"').replace("‘", "'").replace("’", "'")
    return text.encode("latin-1", "replace").decode("latin-1")

def generate_inspection_pdf(inspection):
    """
    Takes an Inspection SQLAlchemy model and generates a comprehensive PDF bytes object.
    """
    pdf = CivilCortexPDF()
    pdf.set_auto_page_break(auto=True, margin=25)
    pdf.add_page()
    
    assessment = None
    observation = None
    if inspection.observations:
        observation = inspection.observations[0]
        assessment = observation.assessment

    # 1. Inspection Overview
    pdf.set_font("helvetica", "B", 13)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "1. Inspection Overview", border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 5, sanitize_text(f"Inspection Record ID: #{inspection.id}"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, sanitize_text(f"Timestamp: {inspection.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    
    crack_type = observation.defect.defect_type if observation and observation.defect else 'Unknown'
    severity = assessment.severity if assessment else 'Unknown'
    
    pdf.cell(0, 5, sanitize_text(f"Target Structure: {str(inspection.building.name if hasattr(inspection, 'building') else 'Building').capitalize()}"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, sanitize_text(f"Identified Defect: {crack_type}"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, sanitize_text(f"Visual Severity: {str(severity).upper()}"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # 2. Key Telemetry & Structural Metrics
    pdf.set_font("helvetica", "B", 13)
    pdf.cell(0, 8, "2. Key Telemetry & Diagnostic Metrics", border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 10)
    risk_score = assessment.risk_score if assessment and assessment.risk_score else "N/A"
    risk_lvl = assessment.risk if assessment and assessment.risk else "N/A"
    priority = assessment.priority if assessment and assessment.priority else "N/A"
    
    pdf.cell(0, 5, sanitize_text(f"Risk Assessment Score: {risk_score}/100"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, sanitize_text(f"Risk Level: {str(risk_lvl).upper().replace('_', ' ')}"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, sanitize_text(f"Intervention Priority: {priority}"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # 3. Official Remediation Strategy & Action Plan
    pdf.set_font("helvetica", "B", 13)
    pdf.cell(0, 8, "3. Official Remediation Strategy & Recommendation", border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 9)
    recommendation_text = assessment.llm_report if assessment and assessment.llm_report else (assessment.repair_recommendation if assessment and assessment.repair_recommendation else "Not available")
    
    cleaned_rec = recommendation_text.replace("### ", "").replace("## ", "").replace("**", "")
    pdf.multi_cell(0, 5, sanitize_text(cleaned_rec), align="L")
    pdf.ln(4)
    
    # 4. Standards Citations
    rag_context = assessment.rag_context if assessment and assessment.rag_context else "Not available"
    if rag_context and rag_context != "Not available":
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(0, 7, "4. Regulatory Standards & Compliance References:", border=False, align="L", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "I", 8)
        pdf.set_text_color(70, 70, 70)
        pdf.multi_cell(0, 4, sanitize_text(rag_context), align="L")
        pdf.set_text_color(0, 0, 0)
        
    # Signature Block
    pdf.ln(12)
    pdf.set_font("helvetica", "B", 9)
    pdf.cell(80, 5, "___________________________________", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(80, 5, "Lead Structural Engineer Signature", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(80, 5, f"Date: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}", border=False, align="C")

    return bytes(pdf.output())
