import os
import io
import base64
import tempfile
from fpdf import FPDF
from datetime import datetime
from PIL import Image

class CivilCortexPDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 18)
        self.set_text_color(0, 51, 102) # Dark blue
        self.cell(0, 10, "CIVILCORTEX ENGINEERING REPORT", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("helvetica", "I", 10)
        self.set_text_color(128, 128, 128)
        self.cell(0, 8, "Structural Health Assessment & Remediation Strategy", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(6)

    def footer(self):
        self.set_y(-25)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 8, "Generated by CivilCortex Multi-Agent Structural Health Platform", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}", border=False, align="C")

def sanitize_text(text: str) -> str:
    """Sanitizes text for standard PDF latin-1 output."""
    if not text:
        return ""
    # Replace Rupee symbol and non-latin symbols with compatible strings
    text = text.replace("₹", "INR ").replace("–", "-").replace("—", "-")
    text = text.replace("“", '"').replace("”", '"').replace("‘", "'").replace("’", "'")
    return text.encode("latin-1", "replace").decode("latin-1")

def generate_inspection_pdf(inspection):
    """
    Takes an Inspection SQLAlchemy model and generates a comprehensive PDF bytes object.
    """
    pdf = CivilCortexPDF()
    pdf.set_auto_page_break(auto=True, margin=25)
    pdf.add_page()
    
    report_data = inspection.full_report_json or {}
    
    # Check if in Demo / Prototype mode
    is_demo = report_data.get("mode") == "demo" or "scenario_id" in report_data or "scenario" in report_data
    if is_demo:
        pdf.set_fill_color(240, 244, 248)
        pdf.set_font("helvetica", "B", 9)
        pdf.set_text_color(0, 51, 102)
        pdf.cell(0, 7, sanitize_text("PROTOTYPE / DEMO MODE: Evaluated under controlled demonstration parameters."), border=1, align="C", fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # 1. Inspection Overview
    pdf.set_font("helvetica", "B", 13)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "1. Inspection Overview", border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 5, sanitize_text(f"Inspection Record ID: #{inspection.id}"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, sanitize_text(f"Timestamp: {inspection.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    
    crack_type = report_data.get('crack_type', 'Unknown')
    severity = report_data.get('severity', 'Unknown')
    
    pdf.cell(0, 5, sanitize_text(f"Target Structure: {str(report_data.get('structure_type', 'Tunnel')).capitalize()}"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, sanitize_text(f"Identified Defect: {crack_type}"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, sanitize_text(f"Visual Severity: {str(severity).upper()}"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # 2. Key Telemetry & Structural Metrics
    pdf.set_font("helvetica", "B", 13)
    pdf.cell(0, 8, "2. Key Telemetry & Diagnostic Metrics", border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 10)
    health = report_data.get("health_score", "N/A")
    cond = report_data.get("condition", "N/A")
    risk_score = report_data.get("risk_score", "N/A")
    risk_lvl = report_data.get("risk_level", "N/A")
    priority = report_data.get("priority", "N/A")
    days = report_data.get("days", "N/A")
    cost = report_data.get("estimated_cost", report_data.get("cost_estimate", "N/A"))
    crew = report_data.get("required_workers", report_data.get("crew_size", "N/A"))
    
    pdf.cell(0, 5, sanitize_text(f"Structural Health Score: {health}/100 ({cond})"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, sanitize_text(f"Risk Assessment: {risk_score}/100 (Level: {str(risk_lvl).upper()})"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, sanitize_text(f"Intervention Priority: {priority} (Turnaround: {days} day(s))"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, sanitize_text(f"Estimated Remediation Cost: {cost}"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, sanitize_text(f"Required Workforce: {crew} technician(s) / engineer(s)"), border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # 3. Official Remediation Strategy & Action Plan
    pdf.set_font("helvetica", "B", 13)
    pdf.cell(0, 8, "3. Official Remediation Strategy & Recommendation", border=False, align="L", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 9)
    recommendation_text = str(report_data.get("recommendation", "No recommendation generated."))
    # Clean markdown headers for plain PDF rendering
    cleaned_rec = recommendation_text.replace("### ", "").replace("## ", "").replace("**", "")
    pdf.multi_cell(0, 5, sanitize_text(cleaned_rec), align="L")
    pdf.ln(4)
    
    # 4. Standards Citations
    rag_context = str(report_data.get("rag_context", ""))
    if rag_context and rag_context != "N/A":
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(0, 7, "4. Regulatory Standards & Compliance References:", border=False, align="L", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "I", 8)
        pdf.set_text_color(70, 70, 70)
        pdf.multi_cell(0, 4, sanitize_text(rag_context), align="L")
        pdf.set_text_color(0, 0, 0)
        
    # Signature Block
    pdf.ln(12)
    pdf.set_font("helvetica", "B", 9)
    pdf.cell(80, 5, "___________________________________", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(80, 5, "Lead Structural Engineer Signature", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(80, 5, f"Date: {datetime.utcnow().strftime('%Y-%m-%d')}", border=False, align="C")

    return bytes(pdf.output())
