"""make structural_element_id nullable

Revision ID: 0009753f8746
Revises: 0f0192995f08
Create Date: 2026-09-15 23:37:57.730143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009753f8746'
down_revision: Union[str, Sequence[str], None] = '0f0192995f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.alter_column('structural_element_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.alter_column('structural_element_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
