"""Add AnalysisJob and update Assessment

Revision ID: 0f0192995f08
Revises: 3033a2436086
Create Date: 2026-09-15 23:01:57.973288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0192995f08'
down_revision: Union[str, Sequence[str], None] = '3033a2436086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['inspection_images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.add_column('assessments', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('assessments', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('assessments', sa.Column('rag_context', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'rag_context')
    op.drop_column('assessments', 'priority')
    op.drop_column('assessments', 'risk_score')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
