"""rename file_path to object_key

Revision ID: 1438001215a5
Revises: 31bd94881352
Create Date: 2026-09-16 00:45:04.265296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1438001215a5'
down_revision: Union[str, Sequence[str], None] = '31bd94881352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_images', schema=None) as batch_op:
        batch_op.alter_column('file_path', new_column_name='object_key', existing_type=sa.String(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_images', schema=None) as batch_op:
        batch_op.alter_column('object_key', new_column_name='file_path', existing_type=sa.String(), existing_nullable=False)

    # ### end Alembic commands ###
