"""Add RBAC and organization_id

Revision ID: 1990d91f683b
Revises: 1438001215a5
Create Date: 2026-09-16 08:44:57.805544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1990d91f683b'
down_revision: Union[str, Sequence[str], None] = '1438001215a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))

    op.execute("UPDATE users SET role = 'INSPECTOR', organization_id = id")
    op.execute("UPDATE buildings SET organization_id = owner_id")

    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.alter_column('organization_id', nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role', nullable=False)
        batch_op.alter_column('organization_id', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('organization_id')
        batch_op.drop_column('role')

    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
