"""Add inspection workflow fields

Revision ID: 81c4220ec43d
Revises: 9d8f7e6c5b4a
Create Date: 2026-09-22 19:24:10.354808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c4220ec43d'
down_revision: Union[str, Sequence[str], None] = '9d8f7e6c5b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_engineer_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), server_default="DRAFT", nullable=False))
        batch_op.create_index(batch_op.f('ix_inspections_assigned_engineer_id'), ['assigned_engineer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_inspections_assigned_engineer_id', 'users', ['assigned_engineer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inspections_assigned_engineer_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inspections_status'))
        batch_op.drop_index(batch_op.f('ix_inspections_assigned_engineer_id'))
        batch_op.drop_column('status')
        batch_op.drop_column('assigned_engineer_id')

    # ### end Alembic commands ###
